name: 02-workflow-event

on: 
    push:
    pull_request:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "triagged by ${{github.event_name}}"
